### ISSUE TITLE
Stating the version in the README

### ISSUE THREAD

**Issue by aaaaaa123456789** [fstirlitz/c-bsp#3]
Since apparently people are using BSP, I decided to bite the bullet and add proper version numbers to the spec; the current version is 0.5.2. (The revision number isn't of much interest here.)

It might be a good idea to reference the implemented version by version number, instead of by date.

**Comment by fstirlitz** [comment]
Fixed in 58abdfa0fdadc563c49e2084b3c4d6e4c07c775b.
